<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2518" started-at="2020-07-08T18:44:02Z" finished-at="2020-07-08T18:44:05Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="2518" started-at="2020-07-08T18:44:02Z" finished-at="2020-07-08T18:44:05Z">
      <class name="org.testing.TestScripts.PostRequestTC">
        <test-method status="PASS" signature="testcase1()[pri:0, instance:org.testing.TestScripts.PostRequestTC@2893de87]" name="testcase1" duration-ms="2196" started-at="2020-07-09T00:14:02Z" finished-at="2020-07-09T00:14:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- org.testing.TestScripts.PostRequestTC -->
      <class name="org.testing.TestScripts.TC8">
        <test-method status="PASS" signature="Testcase8()[pri:0, instance:org.testing.TestScripts.TC8@25b485ba]" name="Testcase8" duration-ms="36" started-at="2020-07-09T00:14:02Z" finished-at="2020-07-09T00:14:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase8 -->
      </class> <!-- org.testing.TestScripts.TC8 -->
      <class name="org.testing.TestScripts.TC7">
        <test-method status="PASS" signature="Testcase7()[pri:0, instance:org.testing.TestScripts.TC7@214b199c]" name="Testcase7" duration-ms="11" started-at="2020-07-09T00:14:02Z" finished-at="2020-07-09T00:14:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase7 -->
      </class> <!-- org.testing.TestScripts.TC7 -->
      <class name="org.testing.TestScripts.TC6">
        <test-method status="PASS" signature="Testcase6()[pri:0, instance:org.testing.TestScripts.TC6@20d3d15a]" name="Testcase6" duration-ms="4" started-at="2020-07-09T00:14:02Z" finished-at="2020-07-09T00:14:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase6 -->
      </class> <!-- org.testing.TestScripts.TC6 -->
      <class name="org.testing.TestScripts.AllGetRequestTC">
        <test-method status="PASS" signature="Testcase3()[pri:0, instance:org.testing.TestScripts.AllGetRequestTC@2c34f934]" name="Testcase3" duration-ms="77" started-at="2020-07-09T00:14:05Z" finished-at="2020-07-09T00:14:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase3 -->
      </class> <!-- org.testing.TestScripts.AllGetRequestTC -->
      <class name="org.testing.TestScripts.DeleteRequestTC">
        <test-method status="PASS" signature="Testcase5()[pri:0, instance:org.testing.TestScripts.DeleteRequestTC@55ca8de8]" name="Testcase5" duration-ms="56" started-at="2020-07-09T00:14:05Z" finished-at="2020-07-09T00:14:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase5 -->
      </class> <!-- org.testing.TestScripts.DeleteRequestTC -->
      <class name="org.testing.TestScripts.PutRequestTC">
        <test-method status="FAIL" signature="Testcase4()[pri:0, instance:org.testing.TestScripts.PutRequestTC@12d3a4e9]" name="Testcase4" duration-ms="41" started-at="2020-07-09T00:14:05Z" finished-at="2020-07-09T00:14:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code is not matching expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code is not matching expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testing.ResponseValidation.ResponseStatusCodeValidate.ResponseStatusValidate(ResponseStatusCodeValidate.java:11)
	at org.testing.TestScripts.PutRequestTC.Testcase4(PutRequestTC.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase4 -->
      </class> <!-- org.testing.TestScripts.PutRequestTC -->
      <class name="org.testing.TestScripts.GetRequestTC">
        <test-method status="FAIL" signature="testcase2()[pri:0, instance:org.testing.TestScripts.GetRequestTC@240237d2]" name="testcase2" duration-ms="33" started-at="2020-07-09T00:14:05Z" finished-at="2020-07-09T00:14:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code is not matching expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code is not matching expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testing.ResponseValidation.ResponseStatusCodeValidate.ResponseStatusValidate(ResponseStatusCodeValidate.java:11)
	at org.testing.TestScripts.GetRequestTC.testcase2(GetRequestTC.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
      </class> <!-- org.testing.TestScripts.GetRequestTC -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
